# numpy基础

### 七月在线python数据分析班 2017升级版 julyedu.com

褚则伟 zeweichu@gmail.com

## Numpy简介

- Numpy是Python语言的一个library [numpy](http://www.numpy.org/)
- Numpy主要支持矩阵操作和运算
- Numpy非常高效，core代码由C语言写成
- 我们第三课要讲的pandas也是基于Numpy构建的一个library
- 现在比较流行的机器学习框架（例如Tensorflow/PyTorch等等），语法都与Numpy比较接近

## 目录
- 数组简介和数组的构造(ndarray)
- 数组取值和赋值
- 数学运算
- broadcasting
- 逻辑运算
- 数组高级操作
- 文件输入输出
- 随堂小项目：用Numpy写一个Softmax

python里面调用一个包，用import对吧, 所以我们import `numpy` 包:

In [88]:
import numpy as np

## Arrays/数组

### 七月在线python数据分析班 2017升级版 julyedu.com

看你数组的维度啦，我自己的话比较简单粗暴，一般直接把1维数组就看做向量/vector，2维数组看做2维矩阵，3维数组看做3维矩阵...

可以调用np.array去从list初始化一个数组:

In [89]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [90]:
print(type(a))

<class 'numpy.ndarray'>


In [91]:
type([1,2,3])

list

In [92]:
a[2]

3

In [93]:
a[0] = 5

In [94]:
print(a)

[5 2 3]


In [95]:
b = np.array([[1,2,3], [2,3,4]])
print(b)

[[1 2 3]
 [2 3 4]]


In [96]:
print(type(b))

<class 'numpy.ndarray'>


In [97]:
print(b.shape)

(2, 3)


In [98]:
print(b[0,2])

3


ndarray = n dimensional array

有一些内置的创建数组的函数:

In [99]:
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [100]:
b = np.ones((1,2))
print(b)

[[1. 1.]]


In [101]:
c = np.full((2,2), 8)
print(c)

[[8 8]
 [8 8]]


In [102]:
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [103]:
e = np.random.random((3,2))
print(e)

[[0.50926869 0.31146102]
 [0.50551632 0.15032224]
 [0.75181674 0.74047255]]


In [104]:
f = np.empty((2,3,4))
print(f)

[[[6.23042070e-307 4.67296746e-307 1.69121096e-306 9.34604357e-307]
  [1.33508845e-306 1.33511969e-306 6.23037996e-307 1.69121639e-306]
  [8.45593934e-307 9.34605716e-307 1.60218491e-306 1.02360867e-306]]

 [[8.01097889e-307 1.78020169e-306 7.56601165e-307 1.02359984e-306]
  [1.33510679e-306 2.22522597e-306 1.24611674e-306 1.29061821e-306]
  [6.23057349e-307 1.86920193e-306 9.34608432e-307 2.56765117e-312]]]


In [105]:
print(f.shape)

(2, 3, 4)


In [106]:
g = np.arange(15)
print(g)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [107]:
print(g.shape)

(15,)


In [108]:
type((2,3))

tuple

数组可以有不同的数据类型

In [109]:
arr = np.array([1,2,3])
print(arr.dtype)

int32


In [110]:
arr = np.array([1,2,3], dtype=np.float64)
print(arr.dtype)

float64


In [111]:
arr

array([1., 2., 3.])

In [112]:
arr = np.array([1,2,3], dtype=np.int64)
print(arr.dtype)

int64


生成数组时可以指定数据类型，如果不指定numpy会自动匹配合适的类型

使用astype复制数组并转换数据类型

In [113]:
int_arr = np.array([1,2,3,4,5])
print(int_arr, int_arr.dtype)

[1 2 3 4 5] int32


In [114]:
float_arr = int_arr.astype(np.float64)
print(float_arr.dtype, float_arr)

float64 [1. 2. 3. 4. 5.]


使用astype将float转换为int时小数部分被舍弃

In [115]:
float_arr = np.array([3.5,2.3,4.8,-2.2])
print(float_arr)

[ 3.5  2.3  4.8 -2.2]


In [116]:
int_arr = float_arr.astype(np.int64)
print(int_arr, int_arr.dtype)

[ 3  2  4 -2] int64


使用astype把字符串转换为数组，如果失败抛出异常。

In [117]:
str_arr = np.array(['1.24', '2.2', '5.8', 'asas'], dtype=np.string_)
str_arr

array([b'1.24', b'2.2', b'5.8', b'asas'], dtype='|S4')

In [118]:
float_arr = str_arr.astype(dtype=np.float)
print(float_arr)

ValueError: could not convert string to float: 'asas'

astype使用其它数组的数据类型作为参数

In [119]:
int_arr = np.arange(10)
float_arr = np.array([2.3,4.6,9.8])
print(float_arr.dtype, int_arr.dtype)

float64 int32


In [120]:
int_arr.astype(dtype=float_arr.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## Array indexing/数组取值和赋值

### 七月在线python数据分析班 2017升级版 julyedu.com

Numpy提供了蛮多种取值的方式的.

In [121]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
print(a.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


可以像list一样切片（多维数组可以从各个维度同时切片）:

In [122]:
b = a[0:2,2:4].copy()
print(b)

[[3 4]
 [7 8]]


虽然，怎么说呢，不建议你这样去赋值，但是你确实可以修改切片出来的对象，然后完成对原数组的赋值.

In [123]:
b[0,0] = 111111
print(b)
print(a)

[[111111      4]
 [     7      8]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


创建3x4的2维数组/矩阵

你就放心大胆地去取你想要的数咯:

In [124]:
row_r1 = a[1,:]
print(row_r1, row_r1.shape)

[5 6 7 8] (4,)


In [125]:
row_r2 = a[1:2, :]
print(row_r2, row_r2.shape)

[[5 6 7 8]] (1, 4)


In [126]:
row_r3 = a[[1], :]
print(row_r3, row_r3.shape)

[[5 6 7 8]] (1, 4)


试试在第2个维度上切片也一样的:

In [127]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [128]:
col_r1 = a[:, 1]
print(col_r1, col_r1.shape)

[ 2  6 10] (3,)


In [129]:
col_r2 = a[:, 1:2]
print(col_r2, col_r2.shape)

[[ 2]
 [ 6]
 [10]] (3, 1)


下面这个高级了，更自由地取值和组合，但是要看清楚一点:

In [130]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [131]:
print(a[[0,1,2], [0,1,0]])
print(a[[0,1,2], [0,1,0]].shape)

[1 4 5]
(3,)


In [132]:
print(np.array([a[0,0], a[1,1], a[2,0]]))

[1 4 5]


In [133]:
print(a)
print(a[[0,0], [1,0]])
print(np.array([a[0,0], a[0,1]]))

[[1 2]
 [3 4]
 [5 6]]
[2 1]
[1 2]


再来熟悉一下

先创建一个2维数组

In [134]:

a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


用下标生成一个向量

In [135]:
b = np.array([0, 2,0,1])

你能看明白下面做的事情吗？

In [136]:
a[np.arange(4), b]

array([ 1,  6,  7, 11])

既然可以取出来，我们当然也可以对这些元素操作咯

In [137]:
a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


比较fashion的取法之一，用条件判定去取（但是很好用）:

In [138]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [139]:
bool_index = (a > 2)
print(bool_index)

[[False False]
 [ True  True]
 [ True  True]]


用刚才的布尔型数组作为下标就可以去除符合条件的元素啦

In [140]:
print(a[bool_index].shape)

(4,)


其实一句话也可以完成是不是？

In [141]:
print(a[a>2])

[3 4 5 6]


那个，真的，其实还有很多细节，其他的方式去取值，你可以看看官方文档。

我们一起来来总结一下，看下面切片取值方式（对应颜色是取出来的结果）：

![](http://old.sebug.net/paper/books/scipydoc/_images/numpy_intro_02.png)
![](http://old.sebug.net/paper/books/scipydoc/_images/numpy_intro_03.png)

#### Datatypes

我们可以用dtype来看numpy数组中元素的类型:

In [142]:
x = np.array([1, 2])  # numpy构建数组的时候自己会确定类型
y = np.array([1.0, 2.0])
z = np.array([1, 2], dtype=np.int64)

In [143]:
print(x.dtype, y.dtype, z.dtype)

int32 float64 int64


更多的内容可以读读[文档](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

## 数学运算
### 七月在线python数据分析班 2017升级版 julyedu.com

下面这些运算才是你在科学运算中经常经常会用到的，比如逐个元素的运算如下:

In [144]:

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [145]:
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [146]:
print(x.shape)
print(y.shape)

(2, 2)
(2, 2)


逐元素求和有下面2种方式

In [147]:
x+y

array([[ 6.,  8.],
       [10., 12.]])

In [148]:
np.add(x,y)

array([[ 6.,  8.],
       [10., 12.]])

逐元素作差

In [149]:
x-y

array([[-4., -4.],
       [-4., -4.]])

In [150]:
np.subtract(x,y)

array([[-4., -4.],
       [-4., -4.]])

逐元素相乘

In [151]:
x*y

array([[ 5., 12.],
       [21., 32.]])

In [152]:
np.multiply(x,y)

array([[ 5., 12.],
       [21., 32.]])

逐元素相除

In [153]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [154]:
np.divide(x, y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [155]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

逐元素求平方根！！！

那如果我要做矩阵的乘法运算怎么办！！！恩，别着急，照着下面写就可以了:

[matrix multiplication](http://mathworld.wolfram.com/MatrixMultiplication.html)

In [156]:
v = np.array([9,10])
w = np.array([10,11])
print(v.shape)

(2,)


求向量内积

In [157]:
v.dot(w)

200

In [158]:
np.dot(v,w)

200

矩阵的乘法

In [159]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])
print(x)
print()
print(y)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


In [160]:
v

array([ 9, 10])

In [161]:
print(x.dot(v))

[29 67]


In [162]:
np.dot(x, v)

array([29, 67])

In [163]:
x.dot(y)

array([[19, 22],
       [43, 50]])

In [164]:
np.dot(x,y)

array([[19, 22],
       [43, 50]])

转置和数学公式一样，简单粗暴

In [165]:
x

array([[1, 2],
       [3, 4]])

In [166]:
x.T

array([[1, 3],
       [2, 4]])

需要说明一下，1维的vector转置还是自己

In [167]:
v.shape

(2,)

In [168]:
v.T.shape

(2,)

2维的就不一样了

In [169]:
w = np.array([[1,2,3]])
print(w, w.shape)

[[1 2 3]] (1, 3)


In [170]:
print(w.T)

[[1]
 [2]
 [3]]


利用转置矩阵做dot product

In [171]:
arr = np.random.randn(6,3)
arr

array([[ 1.61601435,  0.57727975,  0.11863016],
       [ 0.20160216, -0.24646828,  1.40133286],
       [-0.87218279, -0.99324773,  0.12977366],
       [-0.7438627 ,  0.27031551,  0.07851419],
       [ 0.16628532, -0.38581941,  0.7900984 ],
       [ 0.26041057, -1.00338379,  0.99112105]])

In [172]:
print(arr.T.dot(arr))

[[ 4.0616448   1.22297192  0.69210981]
 [ 1.22297192  2.60924571 -1.68388519]
 [ 0.69210981 -1.68388519  3.60738898]]


In [173]:
print(np.dot(arr,arr.T))

[[ 2.95882739  0.34975118 -1.96744663 -1.03673097  0.13972323 -0.04082908]
 [ 0.34975118  2.06512382  0.25082622 -0.10656401  1.23580657  1.68869209]
 [-1.96744663  0.25082622  1.76408508  0.39048304  0.34071702  0.89810446]
 [-1.03673097 -0.10656401  0.39048304  0.63256666 -0.16595249 -0.38712285]
 [ 0.13972323  1.23580657  0.34071702 -0.16595249  0.80076291  1.21351055]
 [-0.04082908  1.68869209  0.89810446 -0.38712285  1.21351055  2.05691363]]


高维的tensor也可以做转置

In [174]:
arr = np.arange(16).reshape(2,2,4)
print(arr, arr.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4)


In [175]:
print(arr.transpose((1,0,2)))

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [176]:
print(arr.transpose((0,2,1)))

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


In [177]:
print(arr.transpose((2,1,0)))

[[[ 0  8]
  [ 4 12]]

 [[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]]


In [178]:
print(arr.swapaxes(1,2))

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


In [179]:
x = np.arange(24).reshape(2,3,4)
y = np.arange(8).reshape(4,2)
print(x)
print()
print(y)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [180]:
print(np.matmul(x,y).shape)

(2, 3, 2)


In [181]:
print(np.dot(x,y).shape)

(2, 3, 2)


In [182]:
x = np.arange(24).reshape(2,3,4)
y = np.arange(16).reshape(2,4,2)
print(x.dot(y).shape)

(2, 3, 2, 2)


In [183]:
np.matmul(x,y).shape

(2, 3, 2)

你猜你做科学运算会最常用到的矩阵内元素的运算是什么？对啦，是求和，用 `sum`可以完成:

In [184]:
x= np.array([[1,2], [3,4]])
print(x)

[[1 2]
 [3 4]]


In [185]:
print(np.sum(x))
print(x.sum())

10
10


In [186]:
print(np.sum(x, axis=0))

[4 6]


In [187]:
print(np.sum(x, axis=1))

[3 7]


In [188]:
print(np.mean(x))
print(np.mean(x, axis=0))
print(np.mean(x, axis=1))

2.5
[2. 3.]
[1.5 3.5]


还有一些其他我们可以想到的运算，比如求和，求平均，求cumulative sum，sumulative product用numpy都可以做到

In [189]:
print(x.cumsum(axis=0))
print(x.cumsum(axis=1))

[[1 2]
 [4 6]]
[[1 3]
 [3 7]]


In [190]:
print(x.cumprod(axis=0))
print(x.cumprod(axis=1))

[[1 2]
 [3 8]]
[[ 1  2]
 [ 3 12]]


我想说最基本的运算就是上面这个样子，更多的运算可能得查查[文档](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

其实除掉基本运算，我们经常还需要做一些操作，比如矩阵的变形，转置和重排等等:

一维数组的排序

In [191]:
arr = np.random.randn(8) * 10
print(arr)

[  3.33651558  -0.0541999    8.67616366  -8.38372567   7.61211038
  18.73528119  -1.24042989 -12.70362429]


In [192]:
arr.sort()
print(arr)

[-12.70362429  -8.38372567  -1.24042989  -0.0541999    3.33651558
   7.61211038   8.67616366  18.73528119]


二维数组也可以在某些维度上排序

In [193]:
arr = np.random.randn(5,3) * 10
print(arr)

[[ 10.78336671  -6.93699691  -1.98889245]
 [  8.35913254   9.51613225 -11.83275629]
 [  6.38789499  -8.82294798  -5.40968478]
 [  7.57887621  -6.04896233   9.68546834]
 [  6.32996636   1.39103749   0.56807233]]


In [194]:
arr.sort(1)
print(arr)

[[ -6.93699691  -1.98889245  10.78336671]
 [-11.83275629   8.35913254   9.51613225]
 [ -8.82294798  -5.40968478   6.38789499]
 [ -6.04896233   7.57887621   9.68546834]
 [  0.56807233   1.39103749   6.32996636]]


下面我们做一个小案例，找出排序后位置在5%的数字

In [195]:
large_arr = np.random.randn(1000)
large_arr.sort()
print(large_arr[int(0.05 * len(large_arr))])

-1.6334581007856983


## Broadcasting
### 七月在线python数据分析班 2017升级版 julyedu.com

这个没想好哪个中文词最贴切，我们暂且叫它“传播吧”:<br>
作用是什么呢，我们设想一个场景，如果要用小的矩阵去和大的矩阵做一些操作，但是希望小矩阵能循环和大矩阵的那些块做一样的操作，那急需要Broadcasting啦

我们要做一件事情，给x的每一行都逐元素加上一个向量，然后生成y

In [196]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
print(x)
print()
print(v)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[1 0 1]


In [197]:
y = np.empty_like(x)
print(y)

[[ -624927897  1071664109   873368314]
 [ 1070853882 -1885182719  1071656240]
 [ 1575976404  1069759938   -97307389]
 [ 1072172769  2126743007  1072148979]]


比较粗暴的方式是，用for循环逐个相加

In [198]:
for i in range(4):
    y[i,:] = x[i,:] + v
    
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


这种方法当然可以啦，问题是不高效嘛，如果你的x矩阵行数非常多，那就很慢的咯:

Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

因为broadcasting的存在，你上面的操作可以简单地汇总成一个求和操作

In [199]:
print(x.shape, v.shape)
x + v

(4, 3) (3,)


array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

当操作两个array时，numpy会逐个比较它们的shape，在下述情况下，两arrays会兼容和输出broadcasting结果：<br>

1. 相等
2. 其中一个为1，（进而可进行拷贝拓展已至，shape匹配）

比如求和的时候有：
```python
Image (3d array):  256 x 256 x 3
Scale (1d array):              3
Result (3d array): 256 x 256 x 3

A      (4d array):  8 x 1 x 6 x 1
B      (3d array):      7 x 1 x 5
Result (4d array):  8 x 7 x 6 x 5

A      (2d array):  5 x 4
B      (1d array):      1
Result (2d array):  5 x 4

A      (2d array):  15 x 3 x 5
B      (1d array):  15 x 1 x 5
Result (2d array):  15 x 3 x 5
```

下面是一些 broadcasting 的例子:

我们来理解一下broadcasting的这种用法

先把v变形成3x1的数组/矩阵，然后就可以broadcasting加在w上了:

In [200]:
v = np.array([1,2,3])
w = np.array([4,5])
print(v.shape, w.shape)

(3,) (2,)


In [201]:
v = v.reshape(3,1)
print(v.shape)

(3, 1)


In [202]:
v + w

array([[5, 6],
       [6, 7],
       [7, 8]])

那如果要把一个矩阵的每一行都加上一个向量呢

In [203]:
x = np.array([[1,2,3], [4,5,6]])
v = np.array([1,2,3])
print(x + v)

[[2 4 6]
 [5 7 9]]


In [204]:

x = np.array([[1,2,3], [4,5,6]]) # 2x3的
w = np.array([4,5]) # 2

In [205]:
(x.T + w).T

array([[ 5,  6,  7],
       [ 9, 10, 11]])

上面那个操作太复杂了，其实我们可以直接这么做嘛

In [206]:
x + np.reshape(w, (2,1))

array([[ 5,  6,  7],
       [ 9, 10, 11]])

broadcasting当然可以逐元素运算了

总结一下broadcasting，可以看看下面的图：<br>
![](http://www.astroml.org/_images/fig_broadcast_visual_1.png)

## 逻辑运算
### 七月在线python数据分析班 2017升级版 julyedu.com

In [207]:

x_arr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
y_arr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [208]:
cond = np.array([True, False, True, True, False])


In [209]:
print(np.where(cond, x_arr, y_arr))

[1.1 2.2 1.3 1.4 2.5]


In [210]:
arr = np.random.randn(4,4)
print(arr)

[[-0.65220622 -0.11975372 -1.67831028  0.64625835]
 [-0.90045827 -0.3624295   0.38723477  0.85060853]
 [-0.93630083 -0.6134299  -0.2325984   0.9425482 ]
 [ 1.4497046  -1.5652444  -0.99044532 -1.24457074]]


In [211]:
arr > 0

array([[False, False, False,  True],
       [False, False,  True,  True],
       [False, False, False,  True],
       [ True, False, False, False]])

In [212]:
print(np.where(arr > 0, 1,-1))

[[-1 -1 -1  1]
 [-1 -1  1  1]
 [-1 -1 -1  1]
 [ 1 -1 -1 -1]]


In [213]:
print(np.where(arr > 0, 1,arr))

[[-0.65220622 -0.11975372 -1.67831028  1.        ]
 [-0.90045827 -0.3624295   1.          1.        ]
 [-0.93630083 -0.6134299  -0.2325984   1.        ]
 [ 1.         -1.5652444  -0.99044532 -1.24457074]]


## 一些更高级的ndarray处理
### 七月在线python数据分析班 2017升级版 julyedu.com

## 使用reshape来改变tensor的形状

numpy可以很容易地把一维数组转成二维数组，三维数组。

In [214]:
arr = np.arange(8)
print(arr.shape)

(8,)


In [215]:
arr.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [216]:
arr.reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [217]:
arr = np.arange(15)
print(arr.reshape(5,3).shape)

(5, 3)


In [218]:
print(arr.reshape(5,-1).shape)

(5, 3)


如果我们在某一个维度上写上-1，numpy会帮我们自动推导出正确的维度

还可以从其他的ndarray中获取shape信息然后reshape

In [219]:
other_arr = np.ones((3,5))
print(other_arr.shape) # tuple

(3, 5)


In [220]:
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

高维数组可以用ravel来拉平

In [221]:
arr = arr.reshape(other_arr.shape)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [222]:
arr.ravel().shape

(15,)

## 连接两个二维数组
### 七月在线python数据分析班 2017升级版 julyedu.com

In [223]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
print(arr1, "\n\n", arr2)

[[1 2 3]
 [4 5 6]] 

 [[ 7  8  9]
 [10 11 12]]


In [224]:
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [225]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

所谓堆叠，参考叠盘子。。。连接的另一种表述
垂直stack与水平stack

In [226]:
np.vstack((arr1, arr2)) # vertical

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [227]:
np.hstack((arr1, arr2)) # horizontal

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

拆分数组

In [228]:
arr = np.random.rand(5,5)
print(arr)

[[0.83573442 0.71007925 0.54651815 0.69973597 0.64743231]
 [0.23738736 0.3590945  0.68978532 0.80654941 0.7329319 ]
 [0.42908855 0.25162056 0.16596834 0.99283181 0.52201048]
 [0.99952871 0.4377795  0.36703447 0.60727398 0.63556315]
 [0.20305485 0.11605062 0.30045299 0.99640437 0.98927861]]


In [229]:
first, second, third = np.split(arr, [1,3], axis=0)
print(first, '\n\n', second, '\n\n', third)

[[0.83573442 0.71007925 0.54651815 0.69973597 0.64743231]] 

 [[0.23738736 0.3590945  0.68978532 0.80654941 0.7329319 ]
 [0.42908855 0.25162056 0.16596834 0.99283181 0.52201048]] 

 [[0.99952871 0.4377795  0.36703447 0.60727398 0.63556315]
 [0.20305485 0.11605062 0.30045299 0.99640437 0.98927861]]


堆叠辅助

In [230]:
arr = np.arange(6)
arr1 = arr.reshape((3, 2))
arr2 = np.random.randn(3, 2)
print(arr1)
print(arr2)

[[0 1]
 [2 3]
 [4 5]]
[[ 0.03293034 -0.59344278]
 [-0.15162054 -0.42722401]
 [ 1.5421545   0.28566552]]


r_用于按行堆叠

In [231]:
print(np.r_[arr1, arr2])
print()

[[ 0.          1.        ]
 [ 2.          3.        ]
 [ 4.          5.        ]
 [ 0.03293034 -0.59344278]
 [-0.15162054 -0.42722401]
 [ 1.5421545   0.28566552]]



c_用于按列堆叠

In [232]:
print(np.c_[np.r_[arr1, arr2], arr])
print()

[[ 0.          1.          0.        ]
 [ 2.          3.          1.        ]
 [ 4.          5.          2.        ]
 [ 0.03293034 -0.59344278  3.        ]
 [-0.15162054 -0.42722401  4.        ]
 [ 1.5421545   0.28566552  5.        ]]



切片直接转为数组

In [233]:
np.c_[1:6, -5:0]

array([[ 1, -5],
       [ 2, -4],
       [ 3, -3],
       [ 4, -2],
       [ 5, -1]])

使用repeat来重复

In [234]:
arr = np.arange(3)
print(arr)

[0 1 2]


In [235]:
print(arr.repeat(3))

[0 0 0 1 1 1 2 2 2]


In [236]:
print(arr.repeat([2,3,5]))

[0 0 1 1 1 2 2 2 2 2]


按元素重复

指定axis来重复

In [237]:
arr = np.random.rand(2,2)
print(arr)

[[0.35571495 0.97421873]
 [0.05929565 0.29267432]]


In [238]:
print(arr.repeat(2, axis=0))

[[0.35571495 0.97421873]
 [0.35571495 0.97421873]
 [0.05929565 0.29267432]
 [0.05929565 0.29267432]]


In [239]:
print(arr.repeat(2, axis=1))

[[0.35571495 0.35571495 0.97421873 0.97421873]
 [0.05929565 0.05929565 0.29267432 0.29267432]]


Tile: 参考贴瓷砖
[numpy tile](https://docs.scipy.org/doc/numpy/reference/generated/numpy.tile.html)

In [240]:
print(arr)
print()
print(np.tile(arr, 2))

[[0.35571495 0.97421873]
 [0.05929565 0.29267432]]

[[0.35571495 0.97421873 0.35571495 0.97421873]
 [0.05929565 0.29267432 0.05929565 0.29267432]]


In [241]:
print(np.tile(arr, (2,3)))

[[0.35571495 0.97421873 0.35571495 0.97421873 0.35571495 0.97421873]
 [0.05929565 0.29267432 0.05929565 0.29267432 0.05929565 0.29267432]
 [0.35571495 0.97421873 0.35571495 0.97421873 0.35571495 0.97421873]
 [0.05929565 0.29267432 0.05929565 0.29267432 0.05929565 0.29267432]]


## numpy的文件输入输出
### 七月在线python数据分析班 2017升级版 julyedu.com

读取csv文件作为数组

In [243]:
arr = np.loadtxt('array_ex.txt', delimiter=',')
print(arr)

[[ 0.580052  0.18673   1.040717  1.134411]
 [ 0.194163 -0.636917 -0.938659  0.124094]
 [-0.12641   0.268607 -0.695724  0.047428]
 [-1.484413  0.004176 -0.744203  0.005487]
 [ 2.302869  0.200131  1.670238 -1.88109 ]
 [-0.19323   1.047233  0.482803  0.960334]]


数组文件读写

In [244]:
arr = np.arange(50).reshape(2,5,5)
print(arr)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]


In [245]:
np.save('some_array', arr)

In [246]:
arr2 = np.load('some_array.npy')
print(arr2)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]


In [247]:
arr3 = np.arange(15).reshape(3,5)
np.savez("array_archive.npz", arr=arr, b=arr2, c=arr3)

In [248]:
arch = np.load('array_archive.npz')
print(arch['arr'])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]


In [249]:
arch['b']

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [250]:
arch['c']

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

多个数组可以一起压缩存储


## 随堂小项目

### 七月在线python数据分析班 2017升级版 julyedu.com

用numpy写一个softmax

[什么是softmax?](http://cs231n.github.io/linear-classify/#softmax)

- 计算exponential
- 按行求和
- 每一行都要除以计算的和

In [251]:
m = np.random.rand(10,10) * 10 + 1000
print(m)

[[1008.21652659 1009.4580121  1002.48139104 1005.61742573 1007.78452594
  1008.64673213 1001.08154984 1001.76014437 1009.75747336 1000.94701364]
 [1001.31980452 1003.30110346 1008.40104799 1005.44127162 1001.58406477
  1000.28382302 1008.65612823 1008.42655688 1006.65074461 1002.67385104]
 [1006.41751222 1006.69795937 1005.90262025 1009.01259013 1005.65347376
  1000.75638452 1008.11951661 1005.99520376 1002.86515806 1005.18012042]
 [1009.70807167 1007.4297301  1004.40523087 1001.33598549 1009.48530944
  1009.4170762  1004.90098639 1006.31441753 1005.171967   1009.48904465]
 [1006.82079238 1005.90316556 1001.36137176 1005.77686679 1006.39635316
  1008.33472415 1005.88829292 1000.18686276 1000.05815152 1006.89924313]
 [1001.83473111 1003.31939697 1002.54154927 1007.63123586 1005.15441353
  1001.66300438 1000.26977755 1000.76908117 1008.45792301 1009.92620233]
 [1006.64674377 1003.53075151 1009.16896557 1000.97536335 1005.78685719
  1002.49929293 1005.01275981 1003.02401809 1000.67637184 

In [252]:
# np.exp(m)
m_row_max = m.max(axis=1).reshape(10,1)
print(m_row_max, m_row_max.shape)

[[1009.75747336]
 [1008.65612823]
 [1009.01259013]
 [1009.70807167]
 [1008.33472415]
 [1009.92620233]
 [1009.16896557]
 [1009.30049219]
 [1009.63966397]
 [1009.84648379]] (10, 1)


In [253]:
m = m - m_row_max
print(m)

[[-1.54094677 -0.29946127 -7.27608232 -4.14004763 -1.97294742 -1.11074123
  -8.67592353 -7.99732899  0.         -8.81045973]
 [-7.33632371 -5.35502477 -0.25508024 -3.21485661 -7.07206347 -8.37230521
   0.         -0.22957135 -2.00538362 -5.98227719]
 [-2.59507791 -2.31463076 -3.10996987  0.         -3.35911636 -8.25620561
  -0.89307352 -3.01738637 -6.14743207 -3.83246971]
 [ 0.         -2.27834157 -5.3028408  -8.37208618 -0.22276223 -0.29099547
  -4.80708528 -3.39365414 -4.53610467 -0.21902702]
 [-1.51393178 -2.43155859 -6.97335239 -2.55785736 -1.93837099  0.
  -2.44643123 -8.14786139 -8.27657264 -1.43548102]
 [-8.09147122 -6.60680535 -7.38465306 -2.29496647 -4.7717888  -8.26319795
  -9.65642477 -9.15712116 -1.46827931  0.        ]
 [-2.5222218  -5.63821407  0.         -8.19360222 -3.38210838 -6.66967265
  -4.15620576 -6.14494748 -8.49259373 -1.73165535]
 [-1.68344649  0.         -9.08859051 -4.12827072 -8.9417513  -3.70561424
  -5.0460759  -1.21517033 -9.16745136 -2.21762202]
 [-8.782

In [254]:
m_exp = np.exp(m)
print(m_exp, m_exp.shape)

[[2.14178227e-01 7.41217431e-01 6.91890866e-04 1.59220931e-02
  1.39046423e-01 3.29314771e-01 1.70645283e-04 3.36359849e-04
  1.00000000e+00 1.49164665e-04]
 [6.51441009e-04 4.72435246e-03 7.74854322e-01 4.01610921e-02
  8.48480491e-04 2.31182015e-04 1.00000000e+00 7.94874254e-01
  1.34608647e-01 2.52307422e-03]
 [7.46400608e-02 9.88026596e-02 4.46022991e-02 1.00000000e+00
  3.47659658e-02 2.59642308e-04 4.09395533e-01 4.89289336e-02
  2.13896745e-03 2.16560654e-02]
 [1.00000000e+00 1.02453979e-01 4.97743391e-03 2.31232658e-04
  8.00305114e-01 7.47519067e-01 8.17164306e-03 3.35857254e-02
  1.07150641e-02 8.03300009e-01]
 [2.20043114e-01 8.78997260e-02 9.36508093e-04 7.74705540e-02
  1.43938235e-01 1.00000000e+00 8.66020986e-02 2.89353512e-04
  2.54407655e-04 2.38000852e-01]
 [3.06139028e-04 1.35114168e-03 6.20705974e-04 1.00764772e-01
  8.46522400e-03 2.57833134e-04 6.40129742e-05 1.05466081e-04
  2.30321456e-01 1.00000000e+00]
 [8.02810400e-02 3.55921926e-03 1.00000000e+00 2.76416376e

In [255]:
m_exp_row_sum = m_exp.sum(axis=1).reshape(10,1)
print(m_exp_row_sum, m_exp_row_sum.shape)

[[2.44102701]
 [2.75347684]
 [1.73519013]
 [3.51125927]
 [1.85543485]
 [1.34225675]
 [1.31436858]
 [1.63873841]
 [1.84063046]
 [2.53497178]] (10, 1)


In [256]:
m_softmax = m_exp / m_exp_row_sum
print(m_softmax)

[[8.77410315e-02 3.03649828e-01 2.83442528e-04 6.52270255e-03
  5.69622632e-02 1.34908287e-01 6.99071670e-05 1.37794399e-04
  4.09663636e-01 6.11073392e-05]
 [2.36588519e-04 1.71577708e-03 2.81409420e-01 1.45855928e-02
  3.08148766e-04 8.39600359e-05 3.63177196e-01 2.88680203e-01
  4.88867910e-02 9.16323019e-04]
 [4.30154942e-02 5.69405381e-02 2.57045602e-02 5.76305723e-01
  2.00358251e-02 1.49633348e-04 2.35936988e-01 2.81980245e-02
  1.23269918e-03 1.24805144e-02]
 [2.84798109e-01 2.91786994e-02 1.41756376e-03 6.58546236e-05
  2.27925383e-01 2.12892017e-01 2.32726849e-03 9.56515107e-03
  3.05162999e-03 2.28778324e-01]
 [1.18593824e-01 4.73741916e-02 5.04737794e-04 4.17533141e-02
  7.75765503e-02 5.38957215e-01 4.66748259e-02 1.55949163e-04
  1.37114841e-04 1.28272277e-01]
 [2.28077846e-04 1.00661940e-03 4.62434608e-04 7.50711606e-02
  6.30670995e-03 1.92089281e-04 4.76905586e-05 7.85737014e-05
  1.71592697e-01 7.45013947e-01]
 [6.10795490e-02 2.70793088e-03 7.60821596e-01 2.10303549e

In [257]:
print(m_softmax.sum(axis=1))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


更多的numpy细节和用法可以查看一下官网[numpy指南](http://docs.scipy.org/doc/numpy/reference/)