# numpy基础

### 七月在线python数据分析班 2017升级版 julyedu.com

褚则伟 zeweichu@gmail.com

## Numpy简介

- Numpy是Python语言的一个library [numpy](http://www.numpy.org/)
- Numpy主要支持矩阵操作和运算
- Numpy非常高效，core代码由C语言写成
- 我们第三课要讲的pandas也是基于Numpy构建的一个library
- 现在比较流行的机器学习框架（例如Tensorflow/PyTorch等等），语法都与Numpy比较接近

## 目录
- 数组简介和数组的构造(ndarray)
- 数组取值和赋值
- 数学运算
- broadcasting
- 逻辑运算
- 数组高级操作
- 文件输入输出
- 随堂小项目：用Numpy写一个Softmax

python里面调用一个包，用import对吧, 所以我们import `numpy` 包:

In [1]:
import numpy as np

## Arrays/数组

### 七月在线python数据分析班 2017升级版 julyedu.com

看你数组的维度啦，我自己的话比较简单粗暴，一般直接把1维数组就看做向量/vector，2维数组看做2维矩阵，3维数组看做3维矩阵...

可以调用np.array去从list初始化一个数组:

In [2]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
type([1,2,3])

list

In [5]:
a[2]

3

In [6]:
a[0] = 5

In [7]:
print(a)

[5 2 3]


In [8]:
b = np.array([[1,2,3], [2,3,4]])
print(b)

[[1 2 3]
 [2 3 4]]


In [9]:
print(type(b))

<class 'numpy.ndarray'>


In [10]:
print(b.shape)

(2, 3)


In [11]:
print(b[0,2])

3


ndarray = n dimensional array

有一些内置的创建数组的函数:

In [12]:
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
b = np.ones((1,2))
print(b)

[[1. 1.]]


In [14]:
c = np.full((2,2), 8)
print(c)

[[8 8]
 [8 8]]


In [15]:
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
e = np.random.random((3,2))
print(e)

[[0.36065746 0.93047873]
 [0.5788435  0.15059019]
 [0.30010097 0.09676462]]


In [17]:
f = np.empty((2,3,4))
print(f)

[[[6.23042070e-307 4.67296746e-307 1.69121096e-306 9.34604357e-307]
  [1.33508845e-306 1.33511969e-306 6.23037996e-307 1.69121639e-306]
  [6.23046484e-307 6.23053954e-307 9.34609790e-307 8.45593934e-307]]

 [[9.34600963e-307 1.86921143e-306 6.23061763e-307 6.89804132e-307]
  [8.45610231e-307 9.34601642e-307 6.89804132e-307 1.11261162e-306]
  [8.34443015e-308 1.78022342e-306 8.06635958e-308 1.42410974e-306]]]


In [18]:
print(f.shape)

(2, 3, 4)


In [19]:
g = np.arange(15)
print(g)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [20]:
print(g.shape)

(15,)


In [21]:
type((2,3))

tuple

数组可以有不同的数据类型

In [22]:
arr = np.array([1,2,3])
print(arr.dtype)

int32


In [23]:
arr = np.array([1,2,3], dtype=np.float64)
print(arr.dtype)

float64


In [24]:
arr

array([1., 2., 3.])

In [25]:
arr = np.array([1,2,3], dtype=np.int64)
print(arr.dtype)

int64


生成数组时可以指定数据类型，如果不指定numpy会自动匹配合适的类型

使用astype复制数组并转换数据类型

In [26]:
int_arr = np.array([1,2,3,4,5])
print(int_arr, int_arr.dtype)

[1 2 3 4 5] int32


In [27]:
float_arr = int_arr.astype(np.float64)
print(float_arr.dtype, float_arr)

float64 [1. 2. 3. 4. 5.]


使用astype将float转换为int时小数部分被舍弃

In [28]:
float_arr = np.array([3.5,2.3,4.8,-2.2])
print(float_arr)

[ 3.5  2.3  4.8 -2.2]


In [29]:
int_arr = float_arr.astype(np.int64)
print(int_arr, int_arr.dtype)

[ 3  2  4 -2] int64


使用astype把字符串转换为数组，如果失败抛出异常。

In [30]:
str_arr = np.array(['1.24', '2.2', '5.8', 'asas'], dtype=np.string_)
str_arr

array([b'1.24', b'2.2', b'5.8', b'asas'], dtype='|S4')

In [31]:
float_arr = str_arr.astype(dtype=np.float)
print(float_arr)

ValueError: could not convert string to float: 'asas'

astype使用其它数组的数据类型作为参数

In [32]:
int_arr = np.arange(10)
float_arr = np.array([2.3,4.6,9.8])
print(float_arr.dtype, int_arr.dtype)

float64 int32


In [33]:
int_arr.astype(dtype=float_arr.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## Array indexing/数组取值和赋值

### 七月在线python数据分析班 2017升级版 julyedu.com

Numpy提供了蛮多种取值的方式的.

In [34]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
print(a.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


可以像list一样切片（多维数组可以从各个维度同时切片）:

In [35]:
b = a[0:2,2:4].copy()
print(b)

[[3 4]
 [7 8]]


虽然，怎么说呢，不建议你这样去赋值，但是你确实可以修改切片出来的对象，然后完成对原数组的赋值.

In [36]:
b[0,0] = 111111
print(b)
print(a)

[[111111      4]
 [     7      8]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


创建3x4的2维数组/矩阵

你就放心大胆地去取你想要的数咯:

In [37]:
row_r1 = a[1,:]
print(row_r1, row_r1.shape)

[5 6 7 8] (4,)


In [38]:
row_r2 = a[1:2, :]
print(row_r2, row_r2.shape)

[[5 6 7 8]] (1, 4)


In [39]:
row_r3 = a[[1], :]
print(row_r3, row_r3.shape)

[[5 6 7 8]] (1, 4)


试试在第2个维度上切片也一样的:

In [40]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
col_r1 = a[:, 1]
print(col_r1, col_r1.shape)

[ 2  6 10] (3,)


In [42]:
col_r2 = a[:, 1:2]
print(col_r2, col_r2.shape)

[[ 2]
 [ 6]
 [10]] (3, 1)


下面这个高级了，更自由地取值和组合，但是要看清楚一点:

In [43]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [44]:
print(a[[0,1,2], [0,1,0]])
print(a[[0,1,2], [0,1,0]].shape)

[1 4 5]
(3,)


In [45]:
print(np.array([a[0,0], a[1,1], a[2,0]]))

[1 4 5]


In [46]:
print(a)
print(a[[0,0], [1,0]])
print(np.array([a[0,0], a[0,1]]))

[[1 2]
 [3 4]
 [5 6]]
[2 1]
[1 2]


再来熟悉一下

先创建一个2维数组

In [47]:

a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


用下标生成一个向量

In [48]:
b = np.array([0, 2,0,1])

你能看明白下面做的事情吗？

In [49]:
a[np.arange(4), b]

array([ 1,  6,  7, 11])

既然可以取出来，我们当然也可以对这些元素操作咯

In [50]:
a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


比较fashion的取法之一，用条件判定去取（但是很好用）:

In [51]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [52]:
bool_index = (a > 2)
print(bool_index)

[[False False]
 [ True  True]
 [ True  True]]


用刚才的布尔型数组作为下标就可以去除符合条件的元素啦

In [53]:
print(a[bool_index].shape)

(4,)


其实一句话也可以完成是不是？

In [54]:
print(a[a>2])

[3 4 5 6]


那个，真的，其实还有很多细节，其他的方式去取值，你可以看看官方文档。

我们一起来来总结一下，看下面切片取值方式（对应颜色是取出来的结果）：

![](http://old.sebug.net/paper/books/scipydoc/_images/numpy_intro_02.png)
![](http://old.sebug.net/paper/books/scipydoc/_images/numpy_intro_03.png)

#### Datatypes

我们可以用dtype来看numpy数组中元素的类型:

In [55]:
x = np.array([1, 2])  # numpy构建数组的时候自己会确定类型
y = np.array([1.0, 2.0])
z = np.array([1, 2], dtype=np.int64)

In [56]:
print(x.dtype, y.dtype, z.dtype)

int32 float64 int64


更多的内容可以读读[文档](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

## 数学运算
### 七月在线python数据分析班 2017升级版 julyedu.com

下面这些运算才是你在科学运算中经常经常会用到的，比如逐个元素的运算如下:

In [57]:

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [58]:
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [59]:
print(x.shape)
print(y.shape)

(2, 2)
(2, 2)


逐元素求和有下面2种方式

In [60]:
x+y

array([[ 6.,  8.],
       [10., 12.]])

In [61]:
np.add(x,y)

array([[ 6.,  8.],
       [10., 12.]])

逐元素作差

In [62]:
x-y

array([[-4., -4.],
       [-4., -4.]])

In [63]:
np.subtract(x,y)

array([[-4., -4.],
       [-4., -4.]])

逐元素相乘

In [64]:
x*y

array([[ 5., 12.],
       [21., 32.]])

In [65]:
np.multiply(x,y)

array([[ 5., 12.],
       [21., 32.]])

逐元素相除

In [66]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [67]:
np.divide(x, y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [68]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

逐元素求平方根！！！

那如果我要做矩阵的乘法运算怎么办！！！恩，别着急，照着下面写就可以了:

[matrix multiplication](http://mathworld.wolfram.com/MatrixMultiplication.html)

In [69]:
v = np.array([9,10])
w = np.array([10,11])
print(v.shape)

(2,)


求向量内积

In [70]:
v.dot(w)

200

In [71]:
np.dot(v,w)

200

矩阵的乘法

In [72]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])
print(x)
print()
print(y)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


In [73]:
v

array([ 9, 10])

In [74]:
print(x.dot(v))

[29 67]


In [75]:
np.dot(x, v)

array([29, 67])

In [76]:
x.dot(y)

array([[19, 22],
       [43, 50]])

In [77]:
np.dot(x,y)

array([[19, 22],
       [43, 50]])

转置和数学公式一样，简单粗暴

In [78]:
x

array([[1, 2],
       [3, 4]])

In [79]:
x.T

array([[1, 3],
       [2, 4]])

需要说明一下，1维的vector转置还是自己

In [80]:
v.shape

(2,)

In [81]:
v.T.shape

(2,)

2维的就不一样了

In [82]:
w = np.array([[1,2,3]])
print(w, w.shape)

[[1 2 3]] (1, 3)


In [83]:
print(w.T)

[[1]
 [2]
 [3]]


利用转置矩阵做dot product

In [84]:
arr = np.random.randn(6,3)
arr

array([[ 1.74704154, -1.48962408, -1.45168576],
       [ 0.10465025, -1.47903712,  0.61381319],
       [-1.37455731, -0.78213687,  1.60599901],
       [ 1.56993868, -1.3004524 ,  1.08978425],
       [-0.01755283, -0.49812285, -0.05127175],
       [ 0.53186429, -0.68843458,  1.9789961 ]])

In [85]:
print(arr.T.dot(arr))

[[ 7.70040881 -4.08116563 -1.91510552]
 [-4.08116563  7.43151377 -2.75557973]
 [-1.91510552 -2.75557973 10.17007507]]


In [86]:
print(np.dot(arr,arr.T))

[[ 7.37852558  1.49497377 -3.56772469  3.09790903  0.78578073 -0.91818272]
 [ 1.49497377  2.57526911  1.99874508  2.75663579  0.703434    2.28861393]
 [-3.56772469  1.99874508  5.08037869  0.60935351  0.33138524  2.9856379 ]
 [ 3.09790903  2.75663579  0.60935351  5.34351363  0.56435304  3.88694951]
 [ 0.78578073  0.703434    0.33138524  0.56435304  0.25106327  0.23212267]
 [-0.91818272  2.28861393  2.9856379   3.88694951  0.23212267  4.67324737]]


高维的tensor也可以做转置

In [87]:
arr = np.arange(16).reshape(2,2,4)
print(arr, arr.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4)


In [88]:
print(arr.transpose((1,0,2)))

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [89]:
print(arr.transpose((0,2,1)))

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


In [90]:
print(arr.transpose((2,1,0)))

[[[ 0  8]
  [ 4 12]]

 [[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]]


In [91]:
print(arr.swapaxes(1,2))

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


In [92]:
x = np.arange(24).reshape(2,3,4)
y = np.arange(8).reshape(4,2)
print(x)
print()
print(y)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [93]:
print(np.matmul(x,y).shape)

(2, 3, 2)


In [94]:
print(np.dot(x,y).shape)

(2, 3, 2)


In [95]:
x = np.arange(24).reshape(2,3,4)
y = np.arange(16).reshape(2,4,2)
print(x.dot(y).shape)

(2, 3, 2, 2)


In [96]:
np.matmul(x,y).shape

(2, 3, 2)

你猜你做科学运算会最常用到的矩阵内元素的运算是什么？对啦，是求和，用 `sum`可以完成:

In [97]:
x= np.array([[1,2], [3,4]])
print(x)

[[1 2]
 [3 4]]


In [98]:
print(np.sum(x))
print(x.sum())

10
10


In [99]:
print(np.sum(x, axis=0))

[4 6]


In [100]:
print(np.sum(x, axis=1))

[3 7]


In [101]:
print(np.mean(x))
print(np.mean(x, axis=0))
print(np.mean(x, axis=1))

2.5
[2. 3.]
[1.5 3.5]


还有一些其他我们可以想到的运算，比如求和，求平均，求cumulative sum，sumulative product用numpy都可以做到

In [102]:
print(x.cumsum(axis=0))
print(x.cumsum(axis=1))

[[1 2]
 [4 6]]
[[1 3]
 [3 7]]


In [103]:
print(x.cumprod(axis=0))
print(x.cumprod(axis=1))

[[1 2]
 [3 8]]
[[ 1  2]
 [ 3 12]]


我想说最基本的运算就是上面这个样子，更多的运算可能得查查[文档](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

其实除掉基本运算，我们经常还需要做一些操作，比如矩阵的变形，转置和重排等等:

一维数组的排序

In [104]:
arr = np.random.randn(8) * 10
print(arr)

[  0.56771224   3.66457114  -4.4953544    0.56525943  13.78496925
   9.72516741   8.39558172 -10.31416926]


In [105]:
arr.sort()
print(arr)

[-10.31416926  -4.4953544    0.56525943   0.56771224   3.66457114
   8.39558172   9.72516741  13.78496925]


二维数组也可以在某些维度上排序

In [106]:
arr = np.random.randn(5,3) * 10
print(arr)

[[ -7.35985091  -7.50878781  -0.6995317 ]
 [-15.08884801  11.66052574 -18.19214108]
 [ -5.93451412   5.44524452   3.59057598]
 [  0.31310201   2.33134791 -14.22308931]
 [  8.46592905  11.51582611   7.56389113]]


In [107]:
arr.sort(1)
print(arr)

[[ -7.50878781  -7.35985091  -0.6995317 ]
 [-18.19214108 -15.08884801  11.66052574]
 [ -5.93451412   3.59057598   5.44524452]
 [-14.22308931   0.31310201   2.33134791]
 [  7.56389113   8.46592905  11.51582611]]


下面我们做一个小案例，找出排序后位置在5%的数字

In [108]:
large_arr = np.random.randn(1000)
large_arr.sort()
print(large_arr[int(0.05 * len(large_arr))])

-1.6139879002020159


## Broadcasting
### 七月在线python数据分析班 2017升级版 julyedu.com

这个没想好哪个中文词最贴切，我们暂且叫它“传播吧”:<br>
作用是什么呢，我们设想一个场景，如果要用小的矩阵去和大的矩阵做一些操作，但是希望小矩阵能循环和大矩阵的那些块做一样的操作，那急需要Broadcasting啦

我们要做一件事情，给x的每一行都逐元素加上一个向量，然后生成y

In [109]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
print(x)
print()
print(v)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[1 0 1]


In [110]:
y = np.empty_like(x)
print(y)

[[  131070638  1071060227  1436816460]
 [ 1072547451  -847114059  1071810018]
 [  234045876  1069762186 -1220843372]
 [ 1070806234  -558132248  1069073808]]


比较粗暴的方式是，用for循环逐个相加

In [111]:
for i in range(4):
    y[i,:] = x[i,:] + v
    
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


这种方法当然可以啦，问题是不高效嘛，如果你的x矩阵行数非常多，那就很慢的咯:

Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

因为broadcasting的存在，你上面的操作可以简单地汇总成一个求和操作

In [112]:
print(x.shape, v.shape)
x + v

(4, 3) (3,)


array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

当操作两个array时，numpy会逐个比较它们的shape，在下述情况下，两arrays会兼容和输出broadcasting结果：<br>

1. 相等
2. 其中一个为1，（进而可进行拷贝拓展已至，shape匹配）

比如求和的时候有：
```python
Image (3d array):  256 x 256 x 3
Scale (1d array):              3
Result (3d array): 256 x 256 x 3

A      (4d array):  8 x 1 x 6 x 1
B      (3d array):      7 x 1 x 5
Result (4d array):  8 x 7 x 6 x 5

A      (2d array):  5 x 4
B      (1d array):      1
Result (2d array):  5 x 4

A      (2d array):  15 x 3 x 5
B      (1d array):  15 x 1 x 5
Result (2d array):  15 x 3 x 5
```

下面是一些 broadcasting 的例子:

我们来理解一下broadcasting的这种用法

先把v变形成3x1的数组/矩阵，然后就可以broadcasting加在w上了:

In [113]:
v = np.array([1,2,3])
w = np.array([4,5])
print(v.shape, w.shape)

(3,) (2,)


In [114]:
v = v.reshape(3,1)
print(v.shape)

(3, 1)


In [115]:
v + w

array([[5, 6],
       [6, 7],
       [7, 8]])

那如果要把一个矩阵的每一行都加上一个向量呢

In [116]:
x = np.array([[1,2,3], [4,5,6]])
v = np.array([1,2,3])
print(x + v)

[[2 4 6]
 [5 7 9]]


In [117]:

x = np.array([[1,2,3], [4,5,6]]) # 2x3的
w = np.array([4,5]) # 2

In [118]:
(x.T + w).T

array([[ 5,  6,  7],
       [ 9, 10, 11]])

上面那个操作太复杂了，其实我们可以直接这么做嘛

In [119]:
x + np.reshape(w, (2,1))

array([[ 5,  6,  7],
       [ 9, 10, 11]])

broadcasting当然可以逐元素运算了

总结一下broadcasting，可以看看下面的图：<br>
![](http://www.astroml.org/_images/fig_broadcast_visual_1.png)

## 逻辑运算
### 七月在线python数据分析班 2017升级版 julyedu.com

In [120]:

x_arr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
y_arr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [121]:
cond = np.array([True, False, True, True, False])


In [122]:
print(np.where(cond, x_arr, y_arr))

[1.1 2.2 1.3 1.4 2.5]


In [123]:
arr = np.random.randn(4,4)
print(arr)

[[ 0.64009407  0.14578058  1.03249791 -0.02187014]
 [-0.82373886 -0.14926468 -0.28152757 -1.12134666]
 [-0.49644957  0.78867212  0.05925704 -1.75446339]
 [ 0.67380784  0.65010436 -0.17810591  0.02810998]]


In [124]:
arr > 0

array([[ True,  True,  True, False],
       [False, False, False, False],
       [False,  True,  True, False],
       [ True,  True, False,  True]])

In [125]:
print(np.where(arr > 0, 1,-1))

[[ 1  1  1 -1]
 [-1 -1 -1 -1]
 [-1  1  1 -1]
 [ 1  1 -1  1]]


In [126]:
print(np.where(arr > 0, 1,arr))

[[ 1.          1.          1.         -0.02187014]
 [-0.82373886 -0.14926468 -0.28152757 -1.12134666]
 [-0.49644957  1.          1.         -1.75446339]
 [ 1.          1.         -0.17810591  1.        ]]


## 一些更高级的ndarray处理
### 七月在线python数据分析班 2017升级版 julyedu.com

## 使用reshape来改变tensor的形状

numpy可以很容易地把一维数组转成二维数组，三维数组。

In [127]:
arr = np.arange(8)
print(arr.shape)

(8,)


In [128]:
arr.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [129]:
arr.reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [130]:
arr = np.arange(15)
print(arr.reshape(5,3).shape)

(5, 3)


In [131]:
print(arr.reshape(5,-1).shape)

(5, 3)


如果我们在某一个维度上写上-1，numpy会帮我们自动推导出正确的维度

还可以从其他的ndarray中获取shape信息然后reshape

In [132]:
other_arr = np.ones((3,5))
print(other_arr.shape) # tuple

(3, 5)


In [133]:
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

高维数组可以用ravel来拉平

In [134]:
arr = arr.reshape(other_arr.shape)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [135]:
arr.ravel().shape

(15,)

## 连接两个二维数组
### 七月在线python数据分析班 2017升级版 julyedu.com

In [136]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
print(arr1, "\n\n", arr2)

[[1 2 3]
 [4 5 6]] 

 [[ 7  8  9]
 [10 11 12]]


In [137]:
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [138]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

所谓堆叠，参考叠盘子。。。连接的另一种表述
垂直stack与水平stack

In [139]:
np.vstack((arr1, arr2)) # vertical

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [140]:
np.hstack((arr1, arr2)) # horizontal

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

拆分数组

In [141]:
arr = np.random.rand(5,5)
print(arr)

[[0.92984645 0.36865838 0.80549348 0.02445761 0.40442718]
 [0.95882838 0.84828805 0.38167313 0.15174616 0.7282953 ]
 [0.81899342 0.32903025 0.88476407 0.37508725 0.13375353]
 [0.86847088 0.19742558 0.54584067 0.62120605 0.01297783]
 [0.32915842 0.98630605 0.69554468 0.78787808 0.31672874]]


In [142]:
first, second, third = np.split(arr, [1,3], axis=0)
print(first, '\n\n', second, '\n\n', third)

[[0.92984645 0.36865838 0.80549348 0.02445761 0.40442718]] 

 [[0.95882838 0.84828805 0.38167313 0.15174616 0.7282953 ]
 [0.81899342 0.32903025 0.88476407 0.37508725 0.13375353]] 

 [[0.86847088 0.19742558 0.54584067 0.62120605 0.01297783]
 [0.32915842 0.98630605 0.69554468 0.78787808 0.31672874]]


堆叠辅助

In [143]:
arr = np.arange(6)
arr1 = arr.reshape((3, 2))
arr2 = np.random.randn(3, 2)
print(arr1)
print(arr2)

[[0 1]
 [2 3]
 [4 5]]
[[ 2.69500879 -0.44316333]
 [ 0.74529471  1.45676565]
 [ 0.36139219 -0.06875903]]


r_用于按行堆叠

In [144]:
print(np.r_[arr1, arr2])
print()

[[ 0.          1.        ]
 [ 2.          3.        ]
 [ 4.          5.        ]
 [ 2.69500879 -0.44316333]
 [ 0.74529471  1.45676565]
 [ 0.36139219 -0.06875903]]



c_用于按列堆叠

In [145]:
print(np.c_[np.r_[arr1, arr2], arr])
print()

[[ 0.          1.          0.        ]
 [ 2.          3.          1.        ]
 [ 4.          5.          2.        ]
 [ 2.69500879 -0.44316333  3.        ]
 [ 0.74529471  1.45676565  4.        ]
 [ 0.36139219 -0.06875903  5.        ]]



切片直接转为数组

In [146]:
np.c_[1:6, -5:0]

array([[ 1, -5],
       [ 2, -4],
       [ 3, -3],
       [ 4, -2],
       [ 5, -1]])

使用repeat来重复

In [147]:
arr = np.arange(3)
print(arr)

[0 1 2]


In [148]:
print(arr.repeat(3))

[0 0 0 1 1 1 2 2 2]


In [149]:
print(arr.repeat([2,3,5]))

[0 0 1 1 1 2 2 2 2 2]


按元素重复

指定axis来重复

In [150]:
arr = np.random.rand(2,2)
print(arr)

[[0.27657105 0.32794874]
 [0.89307468 0.6424563 ]]


In [151]:
print(arr.repeat(2, axis=0))

[[0.27657105 0.32794874]
 [0.27657105 0.32794874]
 [0.89307468 0.6424563 ]
 [0.89307468 0.6424563 ]]


In [152]:
print(arr.repeat(2, axis=1))

[[0.27657105 0.27657105 0.32794874 0.32794874]
 [0.89307468 0.89307468 0.6424563  0.6424563 ]]


Tile: 参考贴瓷砖
[numpy tile](https://docs.scipy.org/doc/numpy/reference/generated/numpy.tile.html)

In [153]:
print(arr)
print()
print(np.tile(arr, 2))

[[0.27657105 0.32794874]
 [0.89307468 0.6424563 ]]

[[0.27657105 0.32794874 0.27657105 0.32794874]
 [0.89307468 0.6424563  0.89307468 0.6424563 ]]


In [154]:
print(np.tile(arr, (2,3)))

[[0.27657105 0.32794874 0.27657105 0.32794874 0.27657105 0.32794874]
 [0.89307468 0.6424563  0.89307468 0.6424563  0.89307468 0.6424563 ]
 [0.27657105 0.32794874 0.27657105 0.32794874 0.27657105 0.32794874]
 [0.89307468 0.6424563  0.89307468 0.6424563  0.89307468 0.6424563 ]]


## numpy的文件输入输出
### 七月在线python数据分析班 2017升级版 julyedu.com

读取csv文件作为数组

In [155]:
arr = np.loadtxt('array_ex.txt', delimiter=',')
print(arr)

[[ 0.580052  0.18673   1.040717  1.134411]
 [ 0.194163 -0.636917 -0.938659  0.124094]
 [-0.12641   0.268607 -0.695724  0.047428]
 [-1.484413  0.004176 -0.744203  0.005487]
 [ 2.302869  0.200131  1.670238 -1.88109 ]
 [-0.19323   1.047233  0.482803  0.960334]]


数组文件读写

In [156]:
arr = np.arange(50).reshape(2,5,5)
print(arr)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]


In [157]:
np.save('some_array', arr)

In [158]:
arr2 = np.load('some_array.npy')
print(arr2)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]


In [159]:
arr3 = np.arange(15).reshape(3,5)
np.savez("array_archive.npz", arr=arr, b=arr2, c=arr3)

In [160]:
arch = np.load('array_archive.npz')
print(arch['arr'])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]


In [161]:
arch['b']

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [162]:
arch['c']

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

多个数组可以一起压缩存储


## 随堂小项目

### 七月在线python数据分析班 2017升级版 julyedu.com

用numpy写一个softmax

[什么是softmax?](http://cs231n.github.io/linear-classify/#softmax)

- 计算exponential
- 按行求和
- 每一行都要除以计算的和

In [163]:
m = np.random.rand(10,10) * 10 + 1000
print(m)

[[1005.49822369 1004.27714126 1004.25557042 1001.1011591  1001.83245917
  1005.56596797 1006.73168674 1002.90206884 1002.25584042 1000.92292963]
 [1005.3415521  1003.08030647 1007.43419884 1008.41155585 1001.33720185
  1005.57968403 1006.63146012 1005.3603177  1005.02267808 1000.81930884]
 [1002.01342409 1003.82146083 1009.3560977  1004.20930783 1009.52236129
  1003.0289687  1007.6408229  1008.33057942 1008.76882362 1001.34783612]
 [1006.05277724 1002.4146836  1003.41627266 1002.40474091 1004.43392835
  1002.19448365 1006.83203013 1004.93054825 1006.53859291 1001.13020035]
 [1004.65497201 1009.19944476 1001.93063516 1005.9582792  1002.91099059
  1008.55754986 1007.12093671 1008.03002733 1009.86603126 1009.69168659]
 [1000.91019406 1008.905612   1008.21014613 1003.70406017 1005.09183701
  1009.46366092 1003.05327732 1000.52776717 1002.51438693 1006.48307608]
 [1002.58430478 1002.78453718 1005.44476055 1008.68192432 1001.00706781
  1000.08114341 1009.37865852 1003.0208487  1000.22081231 

In [164]:
# np.exp(m)
m_row_max = m.max(axis=1).reshape(10,1)
print(m_row_max, m_row_max.shape)

[[1006.73168674]
 [1008.41155585]
 [1009.52236129]
 [1006.83203013]
 [1009.86603126]
 [1009.46366092]
 [1009.37865852]
 [1008.02086024]
 [1009.2841638 ]
 [1008.36256071]] (10, 1)


In [165]:
m = m - m_row_max
print(m)

[[-1.23346304 -2.45454547 -2.47611631 -5.63052764 -4.89922756 -1.16571876
   0.         -3.82961789 -4.47584632 -5.80875711]
 [-3.07000375 -5.33124938 -0.97735701  0.         -7.074354   -2.83187182
  -1.78009573 -3.05123815 -3.38887778 -7.59224701]
 [-7.5089372  -5.70090046 -0.16626359 -5.31305346  0.         -6.49339259
  -1.88153838 -1.19178187 -0.75353766 -8.17452517]
 [-0.77925288 -4.41734653 -3.41575747 -4.42728921 -2.39810178 -4.63754648
   0.         -1.90148188 -0.29343722 -5.70182978]
 [-5.21105925 -0.6665865  -7.93539609 -3.90775205 -6.95504066 -1.30848139
  -2.74509455 -1.83600393  0.         -0.17434467]
 [-8.55346685 -0.55804892 -1.25351479 -5.75960075 -4.3718239   0.
  -6.4103836  -8.93589375 -6.94927399 -2.98058484]
 [-6.79435374 -6.59412134 -3.93389797 -0.69673421 -8.37159072 -9.29751512
   0.         -6.35780983 -9.15784621 -0.57510985]
 [-7.10431109  0.         -3.52334524 -2.32545191 -4.04105535 -0.07586785
  -1.72966096 -6.69672539 -6.44092167 -5.78489247]
 [-4.445

In [166]:
m_exp = np.exp(m)
print(m_exp, m_exp.shape)

[[2.91282106e-01 8.59022315e-02 8.40690904e-02 3.58668235e-03
  7.45233732e-03 3.11698544e-01 1.00000000e+00 2.17179126e-02
  1.13805864e-02 3.00115787e-03]
 [4.64209809e-02 4.83802172e-03 3.76304354e-01 1.00000000e+00
  8.46539241e-04 5.89024953e-02 1.68622004e-01 4.73003234e-02
  3.37465268e-02 5.04346508e-04]
 [5.48163366e-04 3.34295392e-03 8.46822994e-01 4.92685977e-03
  1.00000000e+00 1.51340592e-03 1.52355544e-01 3.03679663e-01
  4.70698431e-01 2.81740205e-04]
 [4.58748623e-01 1.20662072e-02 3.28515133e-02 1.19468311e-02
  9.08903193e-02 9.68142208e-03 1.00000000e+00 1.49347141e-01
  7.45696037e-01 3.33984868e-03]
 [5.45589149e-03 5.13458281e-01 3.57850201e-04 2.00856017e-02
  9.53815155e-04 2.70230118e-01 6.42422266e-02 1.59453342e-01
  1.00000000e+00 8.40007322e-01]
 [1.92875269e-04 5.72324627e-01 2.85499560e-01 3.15236994e-03
  1.26281869e-02 1.00000000e+00 1.64439359e-03 1.31580234e-04
  9.59331388e-04 5.07631369e-02]
 [1.12008160e-03 1.36838873e-03 1.95672511e-02 4.98209700e

In [167]:
m_exp_row_sum = m_exp.sum(axis=1).reshape(10,1)
print(m_exp_row_sum, m_exp_row_sum.shape)

[[1.82009065]
 [1.73748559]
 [2.78416976]
 [2.51456794]
 [2.87424445]
 [1.92729606]
 [2.08507003]
 [2.25582707]
 [1.43679866]
 [2.87292008]] (10, 1)


In [168]:
m_softmax = m_exp / m_exp_row_sum
print(m_softmax)

[[1.60037142e-01 4.71966775e-02 4.61895073e-02 1.97060644e-03
  4.09448690e-03 1.71254407e-01 5.49423184e-01 1.19323247e-02
  6.25275804e-03 1.64890571e-03]
 [2.67173329e-02 2.78449602e-03 2.16579841e-01 5.75544341e-01
  4.87220869e-04 3.39009978e-02 9.70494403e-02 2.72234334e-02
  1.94226225e-02 2.90273779e-04]
 [1.96885756e-04 1.20070047e-03 3.04156380e-01 1.76959747e-03
  3.59173502e-01 5.43575305e-04 5.47220742e-02 1.09073688e-01
  1.69062404e-01 1.01193616e-04]
 [1.82436360e-01 4.79852103e-03 1.30644763e-02 4.75104726e-03
  3.61455015e-02 3.85013342e-03 3.97682633e-01 5.93927641e-02
  2.96550364e-01 1.32819982e-03]
 [1.89820024e-03 1.78641132e-01 1.24502354e-04 6.98813275e-03
  3.31849003e-04 9.40177926e-02 2.23509961e-02 5.54766112e-02
  3.47917520e-01 2.92253264e-01]
 [1.00075579e-04 2.96957296e-01 1.48134771e-01 1.63564385e-03
  6.55228182e-03 5.18861643e-01 8.53212758e-04 6.82719361e-05
  4.97760260e-04 2.63390446e-02]
 [5.37191358e-04 6.56279506e-04 9.38445753e-03 2.38941471e

In [169]:
print(m_softmax.sum(axis=1))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


更多的numpy细节和用法可以查看一下官网[numpy指南](http://docs.scipy.org/doc/numpy/reference/)